### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroyItem' of undefined

### ISSUE THREAD

**Issue by kankaristo** [sveale/external-open#3]
Steps to reproduce:
1. Open a file with `external-open`
2. Close "Please wait" tab
3. Close external program

**Atom Version**: 0.207.0
**System**: Ubuntu 14.04.2
**Thrown From**: [external-open](https://github.com/sveale/external-open) package, v0.5.3
### Stack Trace

Uncaught TypeError: Cannot read property 'destroyItem' of undefined

```
At /home/sami/.atom/packages/external-open/lib/external-open.coffee:48

TypeError: Cannot read property 'destroyItem' of undefined
  at /home/sami/.atom/packages/external-open/lib/external-open.coffee:48:57
  at ChildProcess.exithandler (child_process.js:720:7)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Socket.<anonymous> (child_process.js:1166:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "docblockr",
      "git-log",
      "linter-luacheck",
      "autocomplete-clang",
      "atom-ctags",
      "log-console",
      "linter-cpplint"
    ],
    "destroyEmptyPanes": false
  },
  "external-open": {
    "extensions": [
      ".ogg"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-alignment, v0.12.1
atom-fuzzy-grep, v0.2.0
auto-detect-indentation, v0.4.2
autocomplete-glsl, v0.2.3
autocomplete-paths, v1.0.2
branch-status, v0.7.0
build, v0.36.1
clipboard-plus, v0.1.0
editor-stats, v0.17.0
external-open, v0.5.3
file-icons, v1.5.7
file-watcher, v0.3.1
flex-tool-bar, v0.4.2
git-tab-status, v1.9.2
gutter-shadow, v0.4.3
highlight-line, v0.10.2
highlight-selected, v0.9.3
indentation-indicator, v0.5.1
keybinding-cheatsheet, v0.0.9
language-brainfuck, v0.1.0
language-gitignore, v0.2.0
language-glsl, v2.0.0
language-ini, v1.10.0
language-latex, v0.6.1
language-lisp, v0.1.2
language-lua, v0.9.3
language-qml, v1.0.0
language-restructuredtext, v0.6.0
language-svg, v0.8.0
language-swig, v0.1.0
language-x86, v0.1.0
line-diff-details, v1.1.1
line-jumper, v0.14.1
linter, v0.12.6
linter-clang, v2.26.0
linter-coffeelint, v0.3.2
linter-csslint, v0.0.13
linter-flake8, v1.4.2
linter-jscs, v1.12.0
linter-jshint, v0.1.6
linter-less, v0.4.0
linter-lua, v0.1.6
linter-pylint, v0.2.2
linter-shellcheck, v0.0.8
linter-xmllint, v0.0.6
minimap, v4.9.4
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.2.0
open-recent, v2.2.4
overflow, v1.1.1
pigments, v0.4.5
pretty-json, v0.3.3
project-colorize, v0.2.0
project-manager, v1.15.10
revert-buffer, v0.5.0
script, v2.23.0
svg-preview, v0.6.0
symbols-tree-view, v0.9.3
sync-settings, v0.2.2
tab-smart-sort, v0.1.4
tabs-to-spaces, v0.11.0
toggle-packages, v1.0.1
tool-bar, v0.1.5
trailing-spaces, v0.3.0
tree-view-breadcrumb, v0.6.0
tree-view-open-files, v0.2.4
wakatime, v4.0.9
zentabs, v0.8.4

# Dev
atom-fuzzy-grep, v0.2.0
branch-status, v0.7.0
build, v0.36.1
```

**Comment by kankaristo** [comment]
Here's a one character fix. :)

``` coffee
 externalOpenUri = (uri, waitView) ->
   fs ?= require 'fs'
   fs.exists(uri, ((exists) ->
     if (exists)
       open ?= require 'open'
-      open(uri, (=> atom.workspace.paneForItem(waitView).destroyItem(waitView) if waitView?))
+      open(uri, (=> atom.workspace.paneForItem(waitView)?.destroyItem(waitView) if waitView?))
     )
   )
```

**Comment by sveale** [comment]
Thanks! :)
